# CMake generated Testfile for 
# Source directory: /Users/molier/Desktop/Myself/insta360/InstaLibrary-Source/.build-cache/hdr-build-tools/cmake-3.31.12/Tests/FindThreads
# Build directory: /Users/molier/Desktop/Myself/insta360/InstaLibrary-Source/Tests/FindThreads
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[FindThreads.C-only]=] "/Users/molier/Desktop/Myself/insta360/InstaLibrary-Source/bin/ctest" "--build-and-test" "/Users/molier/Desktop/Myself/insta360/InstaLibrary-Source/.build-cache/hdr-build-tools/cmake-3.31.12/Tests/FindThreads/C-only" "/Users/molier/Desktop/Myself/insta360/InstaLibrary-Source/Tests/FindThreads/C-only" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/make" "--build-project" "FindThreads_C-only" "--build-options" "--test-command" "/Users/molier/Desktop/Myself/insta360/InstaLibrary-Source/bin/ctest" "-V")
set_tests_properties([=[FindThreads.C-only]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/molier/Desktop/Myself/insta360/InstaLibrary-Source/.build-cache/hdr-build-tools/cmake-3.31.12/Tests/FindThreads/CMakeLists.txt;2;add_test;/Users/molier/Desktop/Myself/insta360/InstaLibrary-Source/.build-cache/hdr-build-tools/cmake-3.31.12/Tests/FindThreads/CMakeLists.txt;0;")
add_test([=[FindThreads.CXX-only]=] "/Users/molier/Desktop/Myself/insta360/InstaLibrary-Source/bin/ctest" "--build-and-test" "/Users/molier/Desktop/Myself/insta360/InstaLibrary-Source/.build-cache/hdr-build-tools/cmake-3.31.12/Tests/FindThreads/CXX-only" "/Users/molier/Desktop/Myself/insta360/InstaLibrary-Source/Tests/FindThreads/CXX-only" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/make" "--build-project" "FindThreads_CXX-only" "--build-options" "--test-command" "/Users/molier/Desktop/Myself/insta360/InstaLibrary-Source/bin/ctest" "-V")
set_tests_properties([=[FindThreads.CXX-only]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/molier/Desktop/Myself/insta360/InstaLibrary-Source/.build-cache/hdr-build-tools/cmake-3.31.12/Tests/FindThreads/CMakeLists.txt;2;add_test;/Users/molier/Desktop/Myself/insta360/InstaLibrary-Source/.build-cache/hdr-build-tools/cmake-3.31.12/Tests/FindThreads/CMakeLists.txt;0;")
